### ISSUE TITLE
打數字好似search唔到

### ISSUE THREAD

**Issue by patrickfung** [giffon/charleywong#1]
想搵Route 83, 但入’83‘ search唔到, 入‘Route’ search 就ok

**Comment by andyli** [comment]
我用緊 [flexsearch](https://github.com/nextapps-de/flexsearch), 我都發覺係有啲 query 唔係好 handle 到。再之前試過 Lunr.js 同 elasticlunr 都唔係好滿意.
可能試下轉用fuzzy search.

**Comment by andyli** [comment]
前幾日轉咗用 [nroonga](https://github.com/nroonga/nroonga), 感覺 handle 中文字好咗.
告一段落先~
